- repo: git://github.com/dnephin/pre-commit-golang
  sha: 12ebecb5071d6c407f722dfbcc3eb6654b38f3df
  hooks:
    - id: go-vet
    - id: go-lint

- repo: local
  hooks:
  - id: go-imports
    name: Go import
    description: Runs `goimports -w`, requires golang.org/x/tools/cmd/goimports
    language: system
    entry: 'docker-compose run --rm -T base ./resources/dev/go-imports.sh'
    files: \.go$
