version: '2'
services:
  base:
    build:
      context: .
      dockerfile: ./resources/dev/Dockerfile
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - .:/go/src/github.com/dohernandez/market-manager

  http:
    extends: base
    env_file: .env.dev
    depends_on:
      - postgres
    ports:
      - '9082:8081'
    command: "make dev-run-http"

  postgres:
    image: postgres:10.1
    ports:
      - '4532:5432'
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: market-manager-service-dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev4you
