version: '2'
services:
  base:
    build:
      context: .
      dockerfile: ./resources/dev/Dockerfile
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - .:/go/src/github.com/dohernandez/market-manager
